# This is a basic workflow to help you get started with Actions

name: Deploy example site

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com/
        scope: '@ownername'
    - name: install npm
      run: |
        npm i -g gatsby-cli
        npm install     
    - name: gatsby build
      run: |
        echo "-----directory structure--------"
        ls
        echo "-----directory structure--------"
        ls kedro-static-viz-gatsby/src
        echo "------building site--------"
        cd kedro-static-viz-gatsby/ && gatsby build
    - name: Deploy-viz 
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        target_branch: gh-pages
        build_dir: kedro-static-viz-gatsby/public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    - name: create public.tar.gz
      run: |
        cd ~/kedro-static-viz-gatsby/public
        rm *.map
        cd ..
        tar -zcvf public.tar.gz public
        mv public.tar.gz ~/kedro-static-viz
    - name: push public.tar.gz
      uses: github-actions-x/commit@v2.3
      with:
        github-token: ${{ secrets.GITHUB_PAT }}
        push-branch: 'develop'
        commit-message: 'publish'
        force-add: 'true'
        files: ~/public.tar.gz
        name: Public-tar-bot
        email: public-tar-bot@waylonwalker.com
        
        
