# This is a basic workflow to help you get started with Actions

name: Deploy example site

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 11.x
        registry-url: https://npm.pkg.github.com/
        scope: '@ownername'
    - name: install npm
      run: |
        npm install     
    - name: install gatsby-cli
      run: |
        npm i -g gatsby-cli
    - name: gatsby build
      run: |
        echo "-----python version--------"
        python --version
        echo "-----node version--------"
        node -v
        echo "-----gatsby version--------"
        gatsby --version
        echo "-----directory structure--------"
        ls
        echo "-----src directory structure--------"
        ls src
        echo "-----pages directory structure--------"
        ls src/pages
        echo "-----clean--------"
        gatsby clean
        echo "------building site--------"
        gatsby build
    - name: Deploy-viz 
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
